# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  codecov: codecov/codecov@1.1.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.12-node
    working_directory: /go/src/github.com/standup-raven/standup-raven
    steps:
      - checkout
      - restore_cache:
          name: Restore glide dependencies cache
          key: dependency-cache-{{ checksum "./server/glide.lock" }}
      - restore_cache:
          name: Restore webapp dependencies cache
          key: dependency-cache-{{ checksum "./webapp/yarn.lock" }}
      - run: make test
      - codecov/upload:
          file: test.json
      - store_test_results:
          path: coverage.txt
      - run: make check-style
      - run: make dist
      - save_cache:
          name: Save Golang dependencies cache
          key: dependency-cache-{{ checksum "./server/glide.lock" }}
          paths:
            - ./server/vendor
      - save_cache:
          name: Save webapp dependencies cache
          key: dependency-cache-{{ checksum "./webapp/yarn.lock" }}
          paths:
            - ./webapp/node_modules
      - store_artifacts:
          path: ./dist
          destination: build
      - persist_to_workspace:
          root: .
          paths:  
            - dist
  release:
    docker:
      - image: circleci/golang:1.12-node
    working_directory: /go/src/github.com/standup-raven/standup-raven
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make release

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
