# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  codecov: codecov/codecov@1.1.0
  plugin-ci: mattermost/plugin-ci@0.1.4

jobs:
  release:
    docker:
      - image: circleci/golang:1.12-node
    working_directory: /go/src/github.com/standup-raven/standup-raven
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make release

workflows:
  version: 2
  ci:
    jobs:
      - plugin-ci/lint
      - plugin-ci/test
      - plugin-ci/build
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: "Standup Raven - Build & Release"
          requires:
            - plugin-ci/lint
            - plugin-ci/test
            - plugin-ci/build
